### PR TITLE
Update our license on our files

### PR DESCRIPTION
**Pull request by dfed**
Our existing license is incorrect on a per-file basis. This PR fixes that.

### CODE REVIEW

**Review by fdiaz — APPROVED** [review]

**Review by GeorgeLyon — CHANGES_REQUESTED** [review]
Have we talked to a lawyer and asked if this is necessary?

**Comment by dfed** [comment]
@GeorgeLyon open source projects should not state that all rights are reserved. The license text at the top is convention I stole from work I've done on [projects that use Apache 2](https://github.com/square/Valet/blob/master/Sources/Valet/Accessibility.swift#L6) where lawyers were involved.

I can remove the MIT license on each file, but we absolutely should not reserve all rights on an open source project that has a `LICENSE` file that invalidates our rights claim.

@lencioni can you weigh in?

**Comment by GeorgeLyon** [comment]
Yeah, I emailed legal as well (@dfed and @fdiaz are on that email). I'm all for removing the copyright line, but I'd be happier if we could just remove the top-of-file comments entirely.

**Comment by fdiaz** [comment]
I'd prefer if we keep each file with the license as well, that way each of these files individually are explicit about its intent. This is what we've done in [AloeStackView](https://github.com/airbnb/AloeStackView/). Do you foresee any problems with adding the license on top?

**Comment by GeorgeLyon** [comment]
I just think we shouldn't add it if we don't have to, let's wait on an update from legal.

**Comment by fdiaz** [comment]
@GeorgeLyon my point here is less about what we're forced to do and what I think is right for us to do. If someone wants to grab a single file from this project, I think it's nice to have that file explicitly declare its license. That way, anybody using it would immediately know the intent of the file.

I understand that you're reluctant to this change, but if you could expand a bit more on why you think this is undesirable that would be helpful to try to weigh in the different options here.

**Review by GeorgeLyon — APPROVED** [review]
I don't have any problems with folks grabbing files from this problem and using them for literally whatever purpose they want, and I don't see any problems arising if they end up forgetting this code is MIT licensed. I'll unblock this PR since you guys technically own this code and therefore are free to do whatever you want, though I urge you to consider adding the [full text of Andy Weir's "The Egg"](http://www.galactanet.com/oneoff/theegg_mod.html) to the top of every file, instead of the MIT license... it makes for better reading.

**Comment by fdiaz** [comment]
Oh, is the problem that this is too long? We could def trim it down.

What about something like:

```
// MIT License
//
// Copyright (c) 2020 Airbnb
```

Would that work better?

**Comment by lencioni** [comment]
I am not a lawyer, and this is not legal advice, but I think these comments are unnecessary, add noise, and are a likely source of bit-rot. I don't see any value in keeping any of them.

**Comment by GeorgeLyon** [comment]
I would prefer no top-of-file comments, but would settle for just `// Copyright (c) 2020 Airbnb`; if we are feeling fun, something like `// Code for you from Airbnb` or an ASCII Belo.

**Comment by fdiaz** [comment]
I’d say if we’re worried that these don’t add value at all we should just remove it completely. I’m not sure I agree that this doesn’t add value but if people feel passionate about reducing the noise of the file I think it’d be better to remove them instead of keeping something fun on top.

**Pull request merged**
