### PR TITLE
Show Linux support in the README platforms badge

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Comment by fdiaz** [comment]
Should we be adding this to the Package.swift instead?

**Comment by MaxDesiatov** [comment]
Not sure why "instead" and not "in addition to"? Even if Linux was mentioned in any way in `Package.swift`, it would still be useful to advertise Linux support in `README.md`. These are separate things as far as I understand, `README.md` is human-readable, while `Package.swift` is machine-readable.

In terms of `Package.swift`, there's no need to indicate Linux support as it builds already on Linux without a problem. [As was clarified on Swift Forums](https://forums.swift.org/t/platforms-stanza-for-linux/34955/3) the `platforms` configuration in `Package.swift` should be added not to indicate that a certain platform is supported, but [to specify that *only a specific version* of a platform is supported](https://forums.swift.org/t/platforms-stanza-for-linux/34955/13). And there is no way to specify that it builds on *any* Linux. So for example specifying that it builds on Ubuntu will break it on Fedora and vice versa. Thus I'd argue that any mention of Linux should not be added to `Package.swift` to make all possible Linux users happy.

**Comment by fdiaz** [comment]
That makes sense 👍 I was thinking of adding there instead so we can continue using Cocoapods to mantain this badge instead of having to manually update it in the case we want to drop any platform.

I'll let @GeorgeLyon approve and merge.

**Comment by MaxDesiatov** [comment]
CocoaPods does not provide a way to advertise support for Linux or other platforms as far as I'm aware. 

On the matter of other platforms, I think `ResilientDecoding` should [build for WebAssembly](https://swiftwasm.org) without a problem given that Swift Package Manager works with SwiftWasm now. I think I could get a GitHub Action ready to test WebAssembly builds of packages pretty soon (similar to the action that tests the Linux target), so I hope you wouldn't mind if I submit a PR for WebAssembly support at some point 🙂

**Comment by GeorgeLyon** [comment]
I'm a big fan of WebAssembly, but I wouldn't want to pull in an extra dependency into the main project. I would be more in favor of using vanilla WebAssembly rather than something that implements the whole standard library, since `ResilientDecoding` doesn't (to my knowledge) use any POSIX or clib stuff that would make shims necessary. As it stands, I'm not sure there is much benefit to adding the SwiftWasm test case as it would effectively be testing that SwiftWasm does the right thing, rather than anything about the code written in this repo. Testing it in a vanilla wasm environment would enforce that we _don't_ create (or accidentally currently have) a dependency on POSIX or clib which I think would be a positive change.

**Comment by MaxDesiatov** [comment]
To clarify, SwiftWasm doesn't require pulling any dependencies, the project can be built as is, there is also no need for additional test cases. It could be essentially just yet another job in the GitHub Actions config, similarly to what you've got for Linux. SwiftWasm is a vanilla wasm environment, otherwise I'm not sure what would you mean by "non-vanilla" 🙂

**Comment by GeorgeLyon** [comment]
Sure, if it is a PR which just adds a GitHub Action, I'd be open to that.

**Review by GeorgeLyon — APPROVED** [review]

**Pull request merged**
